### ISSUE TITLE
Is composer code true?

### ISSUE THREAD

**Issue by rhnkyr** [akrabat/rka-scheme-and-host-detection-middleware#1]
Hi @akrabat ,

i think your composer installation code is wrong. would it be akrabat/rka-scheme-and-host-detection-middleware ? Btw akrabat/rka-scheme-and-host-detection-middleware does not work either.

**Comment by akrabat** [comment]
Try now. I hadn't registered it with Packagist. It is now though! https://packagist.org/packages/akrabat/rka-scheme-and-host-detection-middleware

**Comment by rhnkyr** [comment]
@akrabat Thanks...
